# Generated by Django 4.2.8 on 2023-12-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.TextField(blank=True, max_length=500)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
